#!/usr/bin/env python

import sys, re
from subprocess import check_output

# git config --global core.hooksPath ~/.personal-git-hooks/

commit_msg_filepath = sys.argv[1]
ingore_branches_list = ["master"]

branch = str(check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip(), encoding="utf-8")
regex = r'(release|bugfix|feature|hotfix)\/(\w+-\d+)'
matched = re.match(regex, branch)

if matched:
    issue = matched.group(2)
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('[%s] %s' % (issue, commit_msg))
elif branch not in ingore_branches_list:
    print(f'Cannot parse branch {branch} name')
    print("Proceed commit? (Y/n):")
    if input().lower() != 'y':
        sys.exit(1)
    sys.exit(0)
